server:
  port: 8080

spring:
  application:
    name: web-application
  thymeleaf:
    cache: false
    enabled: true

# Service URLs - these will be used as fallbacks if service discovery fails
services:
  user-service:
    url: http://localhost:8081
  order-service:
    url: http://localhost:8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true 